title: Ahmad Irfan Syafiq bin Muhammad Rosli
logo: / assets/img/photo_2024-10-15_20-30-42.jpg
description: Final Year Student | Electrical Power Engineering
#show_downloads: true
theme: jekyll-theme-modernist
